### ISSUE TITLE
add an env_remove method

### ISSUE THREAD

**Issue by oconnor663** [oconnor663/duct.py#48]
@iwillspeak already did this on the Rust side: https://github.com/oconnor663/duct.rs/pull/49

**Comment by oconnor663** [comment]
@iwillspeak, not sure if you're interested in the Python side of things, but when I went ahead and pushed this lo and behold there's a test failure on Windows >.<

Turns out that `os.environ` automatically uppercases all the keys you write into it. That's kind of transparent as long as you use `os.environ` directly, but it gets weird as soon as you `copy` it (which we do to make the command context):

```python
import os
os.environ["foo"] = "bar"
print(os.environ.copy()["foo"])  # "bar" on Unix, KeyError on Windows!!!
```

I haven't decided yet exactly what we should do about this. Maybe nothing? The problem is that if you set `"foo"` in the parent environment and then try to `env_remove("foo")`, it's going to do nothing, because by the time our code runs the key is `"FOO"`.

**Comment by oconnor663** [comment]
Decided to uppercase all the variable names on the way into our context, on Windows only.

A test to see what's going on on the Rust side of things: https://github.com/oconnor663/duct.rs/pull/51. I actually don't know whether that's gonna pass :)

**Comment by iwillspeak** [comment]
That's kind of tricky. I guess `env_remove` should casefold the variable then before removing it?

**Comment by oconnor663** [comment]
I think so. Which means that `env` and `full_env` _also_ need to uppercase everything, so that `env_remove` interacts with them properly.
